//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIForm {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class sys : global::System.Configuration.ApplicationSettingsBase {
        
        private static sys defaultInstance = ((sys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new sys())));
        
        public static sys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\Task")]
        public string localWorkspace {
            get {
                return ((string)(this["localWorkspace"]));
            }
            set {
                this["localWorkspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Project\\AB-P-devlis\\")]
        public string localProjectP {
            get {
                return ((string)(this["localProjectP"]));
            }
            set {
                this["localProjectP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Project\\AB-G-devlis\\")]
        public string localProjectG {
            get {
                return ((string)(this["localProjectG"]));
            }
            set {
                this["localProjectG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$/AB-P-devlis")]
        public string vssProjectP {
            get {
                return ((string)(this["vssProjectP"]));
            }
            set {
                this["vssProjectP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$/AB-G-devlis")]
        public string vssProjectG {
            get {
                return ((string)(this["vssProjectG"]));
            }
            set {
                this["vssProjectG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$/B-更新目录/03-数据更新/01核心")]
        public string vssUpdatePath {
            get {
                return ((string)(this["vssUpdatePath"]));
            }
            set {
                this["vssUpdatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABLREQUEST")]
        public string TaskPrex {
            get {
                return ((string)(this["TaskPrex"]));
            }
            set {
                this["TaskPrex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("程宁")]
        public string Author {
            get {
                return ((string)(this["Author"]));
            }
            set {
                this["Author"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jira.abic.com/browse/")]
        public string JiraUrl {
            get {
                return ((string)(this["JiraUrl"]));
            }
            set {
                this["JiraUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******")]
        public string safeIniSrc {
            get {
                return ((string)(this["safeIniSrc"]));
            }
            set {
                this["safeIniSrc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******")]
        public string safeIniDoc {
            get {
                return ((string)(this["safeIniDoc"]));
            }
            set {
                this["safeIniDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\AB-P-Pro")]
        public string localOnlineP {
            get {
                return ((string)(this["localOnlineP"]));
            }
            set {
                this["localOnlineP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\AB-G-Pro")]
        public string localOnlineG {
            get {
                return ((string)(this["localOnlineG"]));
            }
            set {
                this["localOnlineG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$/H-Pro/AB-Pui-Pro")]
        public string vssOnlineP {
            get {
                return ((string)(this["vssOnlineP"]));
            }
            set {
                this["vssOnlineP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$/H-Pro/AB-Gui-Pro")]
        public string vssOnlineG {
            get {
                return ((string)(this["vssOnlineG"]));
            }
            set {
                this["vssOnlineG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\Task\\已经上线")]
        public string OnlineDir {
            get {
                return ((string)(this["OnlineDir"]));
            }
            set {
                this["OnlineDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Temp")]
        public string TempDir {
            get {
                return ((string)(this["TempDir"]));
            }
            set {
                this["TempDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files\\TortoiseGit\\bin\\TortoiseMerge.exe")]
        public string TortoiseMerge {
            get {
                return ((string)(this["TortoiseMerge"]));
            }
            set {
                this["TortoiseMerge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files\\TortoiseGit")]
        public string TortoiseGitRootPath {
            get {
                return ((string)(this["TortoiseGitRootPath"]));
            }
            set {
                this["TortoiseGitRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\Task\\已关闭")]
        public string CloseTaskDir {
            get {
                return ((string)(this["CloseTaskDir"]));
            }
            set {
                this["CloseTaskDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string BackupDay {
            get {
                return ((string)(this["BackupDay"]));
            }
            set {
                this["BackupDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Prefix#-#No#  #Content#  #Author#  #Remark#")]
        public string SvnMessage {
            get {
                return ((string)(this["SvnMessage"]));
            }
            set {
                this["SvnMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string PrefixSep {
            get {
                return ((string)(this["PrefixSep"]));
            }
            set {
                this["PrefixSep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jira.abic.com")]
        public string JiraDomain {
            get {
                return ((string)(this["JiraDomain"]));
            }
            set {
                this["JiraDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jira.abic.com/rest/api/1.0/issues/#taskUID#/watchers")]
        public string JiraWatchUrl {
            get {
                return ((string)(this["JiraWatchUrl"]));
            }
            set {
                this["JiraWatchUrl"] = value;
            }
        }
    }
}
